### ISSUE TITLE
worker_websocket.go 中对 Upgrade 这个 Header 的检查是否有必要？

### ISSUE THREAD

**Issue by zhangnew** [shiyunjin/lan-expose#8]
即使没有这个检查，如果用浏览器直接访问 proxy 服务，在 cmd/proxy/worker.go 中也会检查 Host。
如果是为了防止被攻击，加上 Header 也能轻松绕过。

https://github.com/shiyunjin/lan-expose/blob/70b6af82e9cc3abe899d00e569e2c5a88d57c5b8/cmd/proxy/worker_websocket.go#L14-L21

另外 https://github.com/quic-go/quic-go 这个项目目前支持同时监听 TCP 和 UDP 接口，cmd/proxy/serve.go 中的大部分代码可以用一行 `http3.ListenAndServe(listenAddress, certFile, keyFile, handlerProxy)` 替代，官方示例如下：

https://github.com/quic-go/quic-go/blob/b344940f06b9db32db79dec4c9375825e6a7963a/example/main.go#L183-L186

**Comment by shiyunjin** [comment]
这里检查header头就是为了防止浏览器直接访问proxy服务。这里本质上是为了做向下兼容websocket而留的，其实没有刚需的ws需求是不建议开的。

**Comment by shiyunjin** [comment]
至于使用quic-go同时监听tcp和udp是故意做出区分的。本质上我们只需要quic的udp部分，如果没有ws这件事都不会监听tcp端口。而且其实也无法使用quic-go来实现这个ws的需求，quic-go的tcp监听比起http.server会额外发送alt-svc去升级链接到h3，这就本末倒置了。

**Comment by zhangnew** [comment]
> 这里检查header头就是为了防止浏览器直接访问proxy服务。这里本质上是为了做向下兼容websocket而留的，其实没有刚需的ws需求是不建议开的。

浏览器直接访问的话，cmd/proxy/worker.go 中会检查 Host 不通过的，也相当于解决了这个问题吧。

其实我提出这个问题是，我最近刚开始使用这个项目，然后在对服务做[监控](https://github.com/nezhahq/agent/pull/3) ，发现直接用 curl 请求的话，会走到 websocket 的处理逻辑中；然后发现目前 HTTP/3 协议的支持程度还很低，比如 macos 中 curl 如果要支持  HTTP/3 的话，还需要手动编译 curl，而 Golang 中 http 库目前也并不支持 HTTP/3 协议，所以解决这个问题有几种方案：

1、监控服务改用 HTTP/3 协议请求 UDP 端口
2、worker_websocket.go 中去掉对 Upgrade 头的检查
3、使用 quic-go 监听 TCP 端口，对非 websocket 请求放行，不检查 Upgrade
